### ISSUE TITLE
Expose gdk-x11 with a feature flag

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk-rs#390]
It would be nice to be able to include both gdkx11 & gdkwayland  (once #101  was fixed if ever) directly into the re-exported crates from gtk if those features are enabled. 

Of course, the features shouldn't be set by default. 

It's mostly to avoid having to 
```toml
gdk3x11 = {package = "gdkx11", git = "https://github.com/gtk-rs/gtk-rs", optional = true}
gtk3 = {package = "gtk", git = "https://github.com/gtk-rs/gtk-rs", optional = true}
```

and instead it should probably be
```toml
gtk3 = {git = "https://github.com/gtk-rs/gtk-rs", optional = true, package="gtk", features = ["gdkx11"]}
```
